### PR TITLE
37 json metadata for the mds products

### PR DESCRIPTION
**Pull request by vsmagalhaes**
Added .'kind'_attr file to all products.
The contents of the attribute file are now displayed as Attributes, and the pretty table is deisplayed as contents.

### CODE REVIEW

**Comment by jrhosk** [comment]
@vsmagalhaes I ran the stakeholder notebook in this code, everything looks fine except one questions. Below is the `.image_attr` json. Why are the `grid_size` and `cell_size` empty?

```
{
"version": "0.1.1",
 "origin": "holog", 
"holog_file": "./results/before.holog.zarr",
 "grid_size": "None", 
"cell_size": "None", 
"image_file": "./results/before.image.zarr", 
"padding_factor": 50, 
"parallel": true, 
"grid_interpolation_mode": "linear", 
"chan_average": true, 
"chan_tolerance_factor": 0.005, 
"scan_average": true, 
"ant_list": "all", 
"to_stokes": true, 
"apply_mask": true, 
"phase_fit": true, 
"overwrite": true
}
```

**Comment by vsmagalhaes** [comment]
grid_size and cell_size are None because they are input parameters, and that is what the user gave

**Comment by jrhosk** [comment]
> grid_size and cell_size are None because they are input parameters, and that is what the user gave

The code auto-generates them when the input is `None`, though. Is the meta data created before the grid calculation?

**Comment by vsmagalhaes** [comment]
I store the input dictionary before anything is really done, this is to reflect the user inputs more than anything

**Comment by jrhosk** [comment]
> I store the input dictionary before anything is really done, this is to reflect the user inputs more than anything

If that is the intention, it is working as expected. Those seem like two good candidates to be filled though. They are auto-generated and if the point is to tell user what parameters were used, the default behavior will mean they almost never get written. Just a suggestion to give more info and reduce the number of files; the info gets written for the tests in another file.

**Pull request merged**
