### PR TITLE
256 fix u and v axes in aperture fits files

### PR DESCRIPTION
**Pull request by vsmagalhaes**

### CODE REVIEW

**Comment by jrhosk** [comment]
Should we update the tests before verifying this?

**Comment by vsmagalhaes** [comment]
Yes! I forgot to mention that.
Since the default gridding mode has been changed the tests on center pixel value and similar things need to be updated...

**Comment by vsmagalhaes** [comment]
@jrhosk the unit tests all pass with flying colors.
The test with a hiccup is the stakeholder test that depends on a dropbox hosted JSON that needs to be updated because we have changed the default gridding mode which generates cascading changes in verifying center pixel value and panel shifts.
Do you want me to regenerate `holog_numerical_verification.json` or can you do it?
It has to be done in this branch and I cannot upload it to the dropbox...

**Comment by jrhosk** [comment]
Generate it and send it to me to upload. I was going to fix this by finishing the new code I am writing to administer all of this but it is taking more time than I expected to nail down the API.

**Comment by vsmagalhaes** [comment]
I will generate it and share it with you over gchat.

**Pull request merged**
